# docker-compose.yml
---
version: '2'
services:

  app:
    image: webdevops/php:alpine-php7
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/

  web:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx/h5bp:/etc/nginx/h5bp
      - ./.docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./.docker/nginx/mime.types:/etc/nginx/mime.types
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/site.conf:/etc/nginx/site.conf
    links:
      - app
    depends_on:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=wp-bedrock.docker
      - VIRTUAL_PORT=80

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password

  memcached:
    image: memcached:alpine
