version: '2'
services:
  #######################################
  # Application
  #######################################
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
      - mail
    links:
      - db:db
      - mail:mail
    volumes:
      - ./app:/var/www/html/
    environment:
      - VIRTUAL_HOST=$PROJECT_NAME.docker
      - VIRTUAL_PORT=80
      - DB_NAME=wp
      - DB_USER=wp
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PREFIX=wp_
      - WP_ENV=development
      - WP_HOME=http://$PROJECT_NAME.docker
      - WP_SITEURL=http://$PROJECT_NAME.docker/wp
    extra_hosts:
      - "api.wordpress.org:66.155.40.187"
      - "downloads.wordpress.org:66.155.40.203"

  #######################################
  # Webserver
  #######################################
  web:
    image: nginx:alpine
    volumes:
      - ./.docker/web/h5bp:/etc/nginx/h5bp
      - ./.docker/web/fastcgi_params:/etc/nginx/fastcgi_params
      - ./.docker/web/mime.types:/etc/nginx/mime.types
      - ./.docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/web/site.conf:/etc/nginx/site.conf
    depends_on:
      - app
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=$PROJECT_NAME.docker
      - VIRTUAL_PORT=80

  #######################################
  # Database
  #######################################
  # Enable port mapping to access the database via
  # host: localhost
  # port: 3306
  #######################################
  db:
    image: mariadb
#    ports:
#      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password

  #######################################
  # Mailhog
  #######################################
  # 1. Install a SMTP Plugin, we recommend one of the following:
  #    - https://wordpress.org/plugins/wp-mail-smtp/
  #    - https://wordpress.org/plugins/post-smtp/
  # 2. Set SMTP server hostname to mail
  # 3. Set SMTP port to 1025
  #######################################
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    environment:
      - VIRTUAL_PORT=8025
      - VIRTUAL_HOST=mail.$PROJECT_NAME.docker

# TODO: install composer dependencies via docker
# TODO: dockerize Browsersync/Gulp
